# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/keeping-your-actions-up-to-date-with-dependabot

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    # Limit the number of open PRs to avoid flooding the repo.
    open-pull-requests-limit: 10
    # Add labels for easier filtering.
    labels:
      - "dependencies"
      - "github-actions"
    # Customize commit messages to align with conventional commits.
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
